[project]
name = 'Decentralized-Event-Management-Venue-Coordination'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.attendee-management]
path = 'contracts/attendee-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.event-organizer-verification]
path = 'contracts/event-organizer-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
